# Generated by Django 3.2.9 on 2021-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conred',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.BigIntegerField()),
                ('departamento', models.TextField()),
                ('cod_municipio', models.BigIntegerField()),
                ('municipio', models.TextField()),
                ('eventos_naturales', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('degradacion_ambiental', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inform_humano', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inform_natural', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('peligro_y_exposicion', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('desarrollo_economico', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('desigualdad', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('desarrollo_y_pobreza', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('poblacion_en_dependencia', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('poblacion_desprotegida', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('socioeconomica', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('grupos_vulnerables', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('vulnerabilidades', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('rrd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('gestion_municipal', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('comunicacion', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('infraestructura', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('salud', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inform_institucional', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inform_infraestrucutra', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('falta_capacidad_respuesta', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('inform_risk', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('ranking', models.BigIntegerField()),
                ('missing_indicators', models.BigIntegerField()),
                ('missing_data_p', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
    ]
