# Generated by Django 3.2.9 on 2021-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='riesgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('min_ri', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('max_ri', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color_ri', models.TextField(null=True)),
                ('min_pelyexp', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('max_pelyexp', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color_pelyexp', models.TextField(null=True)),
                ('min_vul', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('max_vul', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color_vul', models.TextField(null=True)),
                ('min_capres', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('max_capres', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('color_capres', models.TextField(null=True)),
            ],
        ),
    ]
