# Generated by Django 3.2.9 on 2021-12-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_db', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
