# Generated by Django 3.2.9 on 2021-12-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indicador_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='nivel',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nivel'),
        ),
    ]
