# Generated by Django 3.2.9 on 2021-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_indicador_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conred',
            name='ranking_dep',
            field=models.BigIntegerField(null=True),
        ),
    ]
